version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: workflow-mysql
    environment:
      MYSQL_DATABASE: workflow_db
      MYSQL_USER: workflow_user
      MYSQL_PASSWORD: workflow_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - workflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workflow-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/workflow_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: workflow_user
      SPRING_DATASOURCE_PASSWORD: workflow_pass
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - workflow-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge

volumes:
  mysql-data:
